#!/usr/bin/env python3
"""
Export Cochrane & Embase manual search strategies from existing Phase 1 data.
==============================================================================
Run this if you already completed Phase 1 but want to (re-)generate the
manual search instruction files without re-calling any LLM.

Usage:
  python scripts/export_manual_queries.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.utils.project import select_project, get_data_dir
from src.utils.query_syntax import build_cochrane_query, build_embase_ovid_query


def main():
    select_project()
    dd = get_data_dir()

    STRATEGY_JSON = f"{dd}/phase1_strategy/search_strategy.json"
    COCHRANE_TXT  = f"{dd}/phase1_strategy/manual_search_cochrane.txt"
    EMBASE_TXT    = f"{dd}/phase1_strategy/manual_search_embase.txt"

    if not Path(STRATEGY_JSON).exists():
        print(f"❌ Strategy file not found: {STRATEGY_JSON}")
        print("   Run Phase 1 first: python scripts/run_phase1.py")
        sys.exit(1)

    strategy = json.loads(Path(STRATEGY_JSON).read_text(encoding="utf-8"))

    flat     = strategy.get("_flat_terms", {})
    mesh     = strategy.get("mesh_terms", {})
    broad    = set(flat.get("broad_terms", []))
    pop_t    = flat.get("population", [])
    int_t    = flat.get("intervention", [])
    mesh_pop = mesh.get("population", [])
    mesh_int = mesh.get("intervention", [])

    # Try to read date range from strategy (may be stored in search_queries/pubmed)
    # Fall back to defaults
    date_start, date_end = "2000", "2025"
    pubmed_q = strategy.get("search_queries", {}).get("pubmed", "")
    import re
    m = re.search(r'(\d{4})/(\d{2}/\d{2})\[dp\]', pubmed_q)
    if m:
        date_start = m.group(1)

    if not pop_t and not int_t:
        print("⚠️  _flat_terms not found in search_strategy.json.")
        print("   This file may have been generated by an older version of the pipeline.")
        print("   Re-run Phase 1 to generate up-to-date manual search files.")
        sys.exit(1)

    cochrane = build_cochrane_query(
        pop_t, int_t, mesh_pop, mesh_int,
        date_start=date_start, date_end=date_end,
        broad_terms=broad,
    )
    embase = build_embase_ovid_query(
        pop_t, int_t, mesh_pop, mesh_int,
        date_start=date_start, date_end=date_end,
        broad_terms=broad,
    )

    Path(COCHRANE_TXT).write_text(cochrane, encoding="utf-8")
    Path(EMBASE_TXT).write_text(embase, encoding="utf-8")

    print("✅ Manual search strategies exported:")
    print(f"   Cochrane Library → {COCHRANE_TXT}")
    print(f"   Embase (Ovid)    → {EMBASE_TXT}")
    print()
    print("Next steps:")
    print(f"  1. Open manual_search_cochrane.txt → run in Cochrane Library Advanced Search")
    print(f"     Export as RIS → save to {dd}/phase2_search/raw/cochrane_search.ris")
    print(f"  2. Open manual_search_embase.txt → run in Ovid Embase")
    print(f"     Verify EMTREE terms first!")
    print(f"     Export as RIS → save to {dd}/phase2_search/raw/embase_export.ris")
    print(f"  3. python scripts/run_phase2.py --deduplicate")


if __name__ == "__main__":
    main()
